jwt:
    secret: 'asdfnsdf4564234324#$@#$4%$^&^%&%^$&$%#$%[][\\[a-zA-z]'

server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/supportportal
        password: root
        username: root
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect   
